# permissions for end users to view catalogues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogue-viewer-role
rules:
- apiGroups:
  - data-mill.cloud
  resources:
  - catalogues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data-mill.cloud
  resources:
  - catalogues/status
  verbs:
  - get
